# This number should be, at maximum, the number of CPU cores on your system.
    worker_processes  auto;
    worker_cpu_affinity auto;
# Number of file descriptors used for Nginx.
    worker_rlimit_nofile 50000;
# Only log critical errors.
    error_log  /var/log/syngx/error.log crit;
    pid        /var/log/syngx/syngx.pid;

events {
    worker_connections  1024;
}

http {
    # Maximum request size configuration to reduce the likelihood of a successful DDoS attack
    include /opt/syngx/conf.d/*.conf;
    client_body_buffer_size      16k;
    client_header_buffer_size    1k;
    client_max_body_size         16M;
    large_client_header_buffers  4 8k;
    # Hide SynGX version number
    server_tokens        off;
    # Hide SynGX name
    more_clear_headers  "Server";
    # Prevents the browser from doing MIME-type sniffing (prevents "mime" based attacks)
    more_set_headers    "X-Content-Type-Options: nosniff";
    # Not be allowed to render a page in a frame
    more_set_headers    "X-Frame-Options: SAMEORIGIN";
    # Enable the cross-site scripting (XSS) filter built into modern web browsers
    more_set_headers    "X-XSS-Protection: 1; mode=block";
    # Hide proxy name
    more_clear_headers   "Server";
    # Hide backend headers
    more_clear_headers  "X-Powered-By";
    # Enabling the header prevents the browser from accessing resources over the HTTP protocol, only HTTPS.
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    
    include       /opt/syngx/conf/mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/syngx/access.log  main;

    sendfile        on;
    # tcp_nopush     on;

    keepalive_timeout  65;

    server {
        listen 8080;
        
        location / {
            add_header  Allow  "GET, HEAD, OPTIONS" always;
            if ( $request_method !~ ^(GET|HEAD|OPTIONS)$ ) {
                return 405;
                }
            root   /opt/syngx/html/;
            index  start_page.html;
        }
        
    }
}
